config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/browse', to: 'home#index', as: :browse
  get 'search', to: 'admin/users#index'
  resources :home, only: [:index, :show]

  namespace :admin do
    resources :dashboard
    resources :active, only: [:index]
    resources :archived, only: [:index]
    resources :items
    resources :users
    resources :search, only: [:index]
  end

  get '/dashboard/:id', to: 'users#show', as: :dashboard
  resources :users
  resources :items
  resources :upvotes


  get '/login', to: 'sessions#new', as: :signup
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authorize_admin
  def index
    @active = Item.all.active.paginate(:page => params[:page])
    @archived = Item.all.archived.paginate(:page => params[:page])
  end
end

app/views/admin/dashboard/index.html.erb
<div class="container">
  <div class="row">
  </div>
  <div class="row">
    <div class="col s12 m6">
      <div class="card-panel dashboard-card">
        <span class="white-text">
          <%= link_to "Add Donation for User", new_admin_item_path %>
        </span>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card-panel dashboard-card">
        <span class="white-text">
          <%= link_to "All Users", admin_users_path, class:"center" %>
        </span>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card-panel dashboard-card">
        <span class="white-text">
          <%= link_to "Active Donations", admin_active_index_path %>
        </span>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card-panel dashboard-card">
        <span class="white-text">
          <%= link_to "Archived Donations", admin_archived_index_path %>
        </span>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card-panel dashboard-card">
        <span class="white-text">
          <%= link_to "Search Donations", admin_search_index_path %>
        </span>
      </div>
    </div>
  </div>
</div>