config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/browse', to: 'home#index', as: :browse
  get 'search', to: 'admin/users#index'
  resources :home, only: [:index, :show]

  namespace :admin do
    resources :dashboard
    resources :active, only: [:index]
    resources :archived, only: [:index]
    resources :items
    resources :users
    resources :search, only: [:index]
  end

  get '/dashboard/:id', to: 'users#show', as: :dashboard
  resources :users
  resources :items
  resources :upvotes


  get '/login', to: 'sessions#new', as: :signup
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/views/shared/_admin_item_card_edit.html.erb
<%= link_to edit_admin_item_path(item) do %>
  <i class="material-icons right">mode_edit</i>
<% end %>
<% if deletable(item) %>
  <% if params[:controller] == "admin/dashboard" %>
    <div class="right"><%= link_to admin_item_path(item, archive: true), method: :put,
      data: {confirm: "Are you sure you want to delete this?"} do %>
      <i class="material-icons right">delete</i>
    <% end %>
    </div>
  <% else %>
    <div class="right"><%= link_to admin_item_path(item, archive: true, user_dash:item.user.id), method: :put,
      data: {confirm: "Are you sure you want to delete this?"} do %>
      <i class="material-icons right">delete</i>
    <% end %>
    </div>
  <% end %>
<% end %>
<% if unarchivable(item) %>
  <% if params[:controller] == "admin/dashboard" %>
    <div class="right"><%= link_to admin_item_path(item, archive: false), method: :put,
      data: {confirm: "Are you sure you want to unarchive this item?"}  do %>
      <i class="material-icons right">add</i>
    <% end %>
    </div>
  <% else %>
    <div class="right"><%= link_to admin_item_path(item, archive: false,
                                                   user_dash: item.user.id), method: :put,
      data: {confirm: "Are you sure you want to unarchive this item?"}  do %>
      <i class="material-icons right">add</i>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_admin_item_show.html.erb
<p><strong>Contact:</strong> <%= item.contact_name %></p>
<p><strong>Address:</strong> <%= formatted_address(item) %></p>
<p><strong>Phone</strong> <%= item.phone %></p>
<p><strong>Email:</strong> <%= item.email %></p>
<p><strong>Delivery:</strong> <%= delivery_option(item) %></p>
<p><strong>User:</strong> <%= item.user.first_name %> <%= item.user.last_name %></p>

app/views/shared/_item_card.html.erb
<div class="col s12 m6 l4">
  <div class="card small s12 m6 l4">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag(item.image.url, class:"activator") %>
    </div>
    <div class="card-content">
      <i class="tiny material-icons activator right">description</i>
      <span class="card-title grey-text text-darken-4"><%= link_to item.name,
        item_path(item.id) %></span>
    </div>
    <div class="card-action upvote-number">
      <span>
        <%= render partial: 'shared/upvote', locals: {item: item} %>
        <% if editable(current_user, item, params[:controller]) %>
          <%= render partial: 'shared/item_card_edit', locals: {item: item} %>
        <% end %>
      </span>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><%= item.name %><i class="material-icons right">close</i></span>
      <p>Retail Value: <strong>$<%= item.retail_value %></strong></p>
      <p><%= item.description %></p>
    </div>
  </div>
</div>

app/views/shared/_item_card_edit.html.erb
<span>
  <div class="right">
    <% if admin? && params[:controller] != "users" %>
      <%= render partial: "shared/admin_item_card_edit", locals: {item: item} %>
  </div>
    <% else %>
      <%= link_to edit_item_path(item) do %>
        <i class="material-icons right">mode_edit</i>
      <% end %>
  </div>
  <% if deletable(item) %>
    <div class="right"><%= link_to item_path(item, archive: true), method: :put,
      data: {confirm: "Are you sure you want to delete this?"} do %>
      <i class="material-icons right">delete</i>
    <% end %>
    </div>
  <% end %>
    <% end %>
</span>

app/views/shared/_nav_links.html.erb
<%= link_to "Add Donation for User", new_admin_item_path %>
<%= link_to "View Users", admin_users_path %>
<%= link_to "View Active Donations", admin_active_index_path %>
<%= link_to "View Archived Donations", admin_archived_index_path %>

app/views/shared/_upvote.html.erb
<% if item_liked?(item) %>
  <%= link_to edit_upvote_path(item, upvote: false), id:"upvote" do %>
    <i class="material-icons left icon-fave">favorite</i>
  <% end %>
<% else %>
  <%= link_to edit_upvote_path(item, upvote: true), id:"upvote" do %>
    <i class="material-icons left">favorite_border</i>
  <% end %>
<% end %>
<%= item.votes_for.size %>