config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/browse', to: 'home#index', as: :browse
  get 'search', to: 'admin/users#index'
  resources :home, only: [:index, :show]

  namespace :admin do
    resources :dashboard
    resources :active, only: [:index]
    resources :archived, only: [:index]
    resources :items
    resources :users
    resources :search, only: [:index]
  end

  get '/dashboard/:id', to: 'users#show', as: :dashboard
  resources :users
  resources :items
  resources :upvotes


  get '/login', to: 'sessions#new', as: :signup
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def index
    @items = Item.active.paginate(:page => params[:page])
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def formatted_address(item)
    "#{item.address} #{item.city}, #{item.state} #{item.zip}"
  end

  def delivery_option(item)
    if item.delivery
      'Delivery available'
    else
      'Pick up required'
    end
  end
end

app/views/home/index.html.erb
<div class="banner">
    <p><%= image_tag("auction.png") %></p>
</div>
<div class="container">
  <div class="row">
    <% @items.each do |item| %>
      <%= render partial: 'shared/item_card', locals: {item: item} %>
     <% end %>
  </div>
  <%= will_paginate @items %>
</div>

app/views/home/oldindexslim.html.slim
.banner
  p = image_tag("auction.png")
.container
  .row
    - @items.each do |item|
      .col.m4
        .card.medium
          .card-image.waves-effect.waves-block.waves-light
            = image_tag(item.image.url(:medium), class:"activator")
          .card-content
            i.tiny.material-icons.activator.right description
            span.card-title.grey-text.text-darken-4 = item.name
            p
              a href="#"  View Item
            .card-action.upvote-number
              span
                = link_to edit_upvote_path(item), id:"upvote", :remote => true do
                  i.material-icons.left thumb_up
                = item.votes_for.size
          .card-reveal
            span.card-title.grey-text.text-darken-4
              = item.name
              i.material-icons.right close
            p = item.description

app/views/home/show.html.erb
<body id="home-welcome">
  <div class="container center home">
    <div class="row banner">
      <p><%= image_tag("auction.png") %></p>
    </div>
    <div class="row banner-buttons">
      <div class="col s12 m6">
        <%= link_to "Donate Items to the Auction", signup_path, class:"btn home" %>
      </div>
      <div class="col s12 m6">
        <%= link_to "Browse Auction Items", browse_path, class:"btn home" %>
      </div>
    </div>
  </div>
</body>