config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/browse', to: 'home#index', as: :browse
  get 'search', to: 'admin/users#index'
  resources :home, only: [:index, :show]

  namespace :admin do
    resources :dashboard
    resources :active, only: [:index]
    resources :archived, only: [:index]
    resources :items
    resources :users
    resources :search, only: [:index]
  end

  get '/dashboard/:id', to: 'users#show', as: :dashboard
  resources :users
  resources :items
  resources :upvotes


  get '/login', to: 'sessions#new', as: :signup
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Sprout City Farms</h5>
        <p class="grey-text text-lighten-4">
          Executive Director: Laura Lavid<br>
          Email: Laura Lavid<br>
          Phone: 720-722-1618
        </p>
      </div>
      <div class="col l4 offset-l2 s12">
        <p class="grey-text text-lighten-4">Mailing Address:<br>
          PO Box 181396
          Denver, CO 80218
        </p>
      </div>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to image_tag("sprout.png"), root_path, class: "brand-logo", width:
      "120px" %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
        <li class="nav-italic">Hi, <%= current_user.first_name.capitalize %></li>
      <% end %>
      <li><%= link_to "Browse", browse_path %></li>
      <% if current_user %>
        <% if admin? %>
          <li><%= link_to "Admin Dashboard", admin_dashboard_index_path %></li>
        <% end %>
        <li><%= link_to "Dashboard", dashboard_path(current_user) %>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
    <ul class="side-nav right" id="mobile-demo">
      <% if current_user %>
        <li class="nav-italic">Hi, <%= current_user.first_name.capitalize %></li>
      <% end %>
      <li><%= link_to "Browse", browse_path %></li>
      <% if current_user %>
        <% if admin? %>
          <li><%= link_to "Admin Dashboard", admin_dashboard_index_path %></li>
        <% end %>
        <li><%= link_to "Dashboard", dashboard_path(current_user) %>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% unless params[:controller] == "home" && params[:action] == "show" %>
        <%= render partial: "layouts/navbar" %>
      <% end %>
    </header>
    <main>
    <% if flash[:notice] %>
      <div class="container">
        <div class="card-panel z-depth-1 success"><%= flash[:notice] %></div>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="container">
        <div class="card-panel z-depth-1 form-error"><%= flash[:error] %></div>
      </div>
    <% end %>
    <%= yield %>
    </main>
    <footer class="page-footer">
      <%= render partial: "layouts/footer" %>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <script src="http://listjs.com/assets/javascripts/list.min.js"></script>
  </body>
</html>